package com.codingfuns.blog.entity;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title4url
     *
     * @mbg.generated
     */
    private String title4url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.ad
     *
     * @mbg.generated
     */
    private String ad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_date
     *
     * @mbg.generated
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.git_url
     *
     * @mbg.generated
     */
    private String gitUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.create_date
     *
     * @return the value of blog.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.create_date
     *
     * @param createDate the value for blog.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.summary
     *
     * @return the value of blog.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.summary
     *
     * @param summary the value for blog.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title4url
     *
     * @return the value of blog.title4url
     *
     * @mbg.generated
     */
    public String getTitle4url() {
        return title4url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title4url
     *
     * @param title4url the value for blog.title4url
     *
     * @mbg.generated
     */
    public void setTitle4url(String title4url) {
        this.title4url = title4url == null ? null : title4url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.ad
     *
     * @return the value of blog.ad
     *
     * @mbg.generated
     */
    public String getAd() {
        return ad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.ad
     *
     * @param ad the value for blog.ad
     *
     * @mbg.generated
     */
    public void setAd(String ad) {
        this.ad = ad == null ? null : ad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_date
     *
     * @return the value of blog.update_date
     *
     * @mbg.generated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_date
     *
     * @param updateDate the value for blog.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.git_url
     *
     * @return the value of blog.git_url
     *
     * @mbg.generated
     */
    public String getGitUrl() {
        return gitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.git_url
     *
     * @param gitUrl the value for blog.git_url
     *
     * @mbg.generated
     */
    public void setGitUrl(String gitUrl) {
        this.gitUrl = gitUrl == null ? null : gitUrl.trim();
    }
}