package com.codingfuns.blog.entity;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.douban_score
     *
     * @mbg.generated
     */
    private Integer doubanScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.readers_num
     *
     * @mbg.generated
     */
    private Integer readersNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.combined_tags
     *
     * @mbg.generated
     */
    private String combinedTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.image_id
     *
     * @mbg.generated
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.translator
     *
     * @mbg.generated
     */
    private String translator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pages
     *
     * @mbg.generated
     */
    private Integer pages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn13
     *
     * @mbg.generated
     */
    private String isbn13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pub_date
     *
     * @mbg.generated
     */
    private String pubDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.douban_score
     *
     * @return the value of book.douban_score
     *
     * @mbg.generated
     */
    public Integer getDoubanScore() {
        return doubanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.douban_score
     *
     * @param doubanScore the value for book.douban_score
     *
     * @mbg.generated
     */
    public void setDoubanScore(Integer doubanScore) {
        this.doubanScore = doubanScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.readers_num
     *
     * @return the value of book.readers_num
     *
     * @mbg.generated
     */
    public Integer getReadersNum() {
        return readersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.readers_num
     *
     * @param readersNum the value for book.readers_num
     *
     * @mbg.generated
     */
    public void setReadersNum(Integer readersNum) {
        this.readersNum = readersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.combined_tags
     *
     * @return the value of book.combined_tags
     *
     * @mbg.generated
     */
    public String getCombinedTags() {
        return combinedTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.combined_tags
     *
     * @param combinedTags the value for book.combined_tags
     *
     * @mbg.generated
     */
    public void setCombinedTags(String combinedTags) {
        this.combinedTags = combinedTags == null ? null : combinedTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.image_id
     *
     * @return the value of book.image_id
     *
     * @mbg.generated
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.image_id
     *
     * @param imageId the value for book.image_id
     *
     * @mbg.generated
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.translator
     *
     * @return the value of book.translator
     *
     * @mbg.generated
     */
    public String getTranslator() {
        return translator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.translator
     *
     * @param translator the value for book.translator
     *
     * @mbg.generated
     */
    public void setTranslator(String translator) {
        this.translator = translator == null ? null : translator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pages
     *
     * @return the value of book.pages
     *
     * @mbg.generated
     */
    public Integer getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pages
     *
     * @param pages the value for book.pages
     *
     * @mbg.generated
     */
    public void setPages(Integer pages) {
        this.pages = pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn13
     *
     * @return the value of book.isbn13
     *
     * @mbg.generated
     */
    public String getIsbn13() {
        return isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn13
     *
     * @param isbn13 the value for book.isbn13
     *
     * @mbg.generated
     */
    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13 == null ? null : isbn13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher
     *
     * @return the value of book.publisher
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher
     *
     * @param publisher the value for book.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pub_date
     *
     * @return the value of book.pub_date
     *
     * @mbg.generated
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pub_date
     *
     * @param pubDate the value for book.pub_date
     *
     * @mbg.generated
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }
}