package com.codingfuns.blog.entity;

import java.util.Date;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.page_num
     *
     * @mbg.generated
     */
    private Integer pageNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.combined_name
     *
     * @mbg.generated
     */
    private String combinedName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbg.generated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbg.generated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.update_time
     *
     * @return the value of tag.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.update_time
     *
     * @param updateTime the value for tag.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.page_num
     *
     * @return the value of tag.page_num
     *
     * @mbg.generated
     */
    public Integer getPageNum() {
        return pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.page_num
     *
     * @param pageNum the value for tag.page_num
     *
     * @mbg.generated
     */
    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.combined_name
     *
     * @return the value of tag.combined_name
     *
     * @mbg.generated
     */
    public String getCombinedName() {
        return combinedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.combined_name
     *
     * @param combinedName the value for tag.combined_name
     *
     * @mbg.generated
     */
    public void setCombinedName(String combinedName) {
        this.combinedName = combinedName == null ? null : combinedName.trim();
    }
}